---
name: Find unformatted files

on: [push, pull_request]

jobs:
  Format:
    name: Find unformatted files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DG
        uses: actions/checkout@v3

      - name: Install latest clang-format
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main"
          sudo apt install clang-format-13

      - name: Find unformatted files
        # Based on https://rigtorp.se/notes/clang-format/.
        run: |
          set -o pipefail
          find . -regextype posix-extended \
                 -iregex '\./(include|lib|tests|tools)/.*\.(h|c|cpp|hpp)' \
                 -o -iregex '\./tests/catch2' -prune -type f | \
              xargs clang-format-13 --style=file --dry-run -Werror --color=true
