---
name: Docker Image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DG
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag dg:$(date +%s)
